### ISSUE TITLE
FrameIT vs. FrameIt in application and Meta INF --> reconcile

### ISSUE THREAD

**Issue by kohlhase** [UFrameIT/UFrameIT#20]
in `MathHub/FrameIT/frameworld/MetaINF/MANIFEST.MF` we find `*FrameIt*` which is very bad (for MMT and IntelliJ) 
BUT the wrong string seems hardcoded into the frameworld game application (when Dennis changed it, it was pushed back)  

This needs to be reconciled. I will refrain from just changing it for the moment.

**Comment by Jazzpirate** [comment]
> BUT the wrong string seems hardcoded into the frameworld game application (when Dennis changed it, it was pushed back)

The more critical issue is differences between git repository names and MMT archive names (in the manifest.mf). A central archive for FrameIT applications should not be called "prototype", particularly not if the git repository is named differently. Same issue: Apparently FrameIT application currently depend on that name, but that should be fixed.

**Comment by richardmarcus** [comment]
Only the server relies on that name (see https://github.com/UFrameIT/mmt-server/blob/master/src/main/scala/com/example/mmtapi/FrameItLogic.scala)

But since this is Scala code and does MMT stuff, I would like to give this task to somebody else (if we want a solution that does not simply change the name at least)

**Comment by kohlhase** [comment]
That looks like @ComFreek  or @Jazzpirate should be able to fix this. Reassigning to Navid.

**Comment by ComFreek** [comment]
This has been fixed long ago.
