### ISSUE TITLE
Do not autoselect a scroll upon game start

### ISSUE THREAD

**Issue by ComFreek** [UFrameIT/UFrameIT#50]
I think it just confuses beginners when a seemingly irrelevant scroll (like MidPoint) is autoselected upon game start.

**Comment by SESch93** [comment]
I have adjusted the code so that a developer can set a field (in the unity-editor) for the preferred Scroll selected on startup. If that field is left empty or no scroll is found with a matching label, no scroll will be selected on startup. For the release I think it's more intuitive if the OppositeLen-Scroll is selected on startup, so I have set the corresponding field.
