### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by ComFreek** [UFrameIT/UFrameIT#9]
The paper currently claimed the license being MIT for the old FrameIT project. What license do we have here? Can we just choose one independent of the assets we copied from the Unity store?

**Comment by kohlhase** [comment]
Yes, the license is something we should think about. I am very much for a GPL3 license and attribute the copyringt to "the KWARC group". 
GPL3 is quite restrictive, I know. But if some external entity gives us good incentives, we can double license (that is why the copyright needs to be with the KWARC group, so that we do not have to chase all the authors after years).

**Comment by ComFreek** [comment]
[Apparently we now have a license.](https://github.com/UFrameIT/UFrameIT/commit/2be92d269a666b09543a39187ab662efc506a614)
